### ISSUE TITLE
Timeout when downloading more than 30ish images

### ISSUE THREAD

**Issue by JustinWingChungHui** [JustinWingChungHui/okkindred_download_images#1]
https://medium.com/coding-xo/azure-function-how-to-change-the-5-minutes-timeout-d930a052d51b

**Comment by ydocsgnillats** [comment]
I think if you increase the function timeout variable in your host.json it will not timeout so quickly.

{
"version": "2.0"
"functionTimeout": "00:10:00"
}

**Comment by JustinWingChungHui** [comment]
Thanks, will give it a go.
